Update US_SteelSection values with high diff
BHoM/BHoM_Datasets pull request #159
Opened 2024-07-08 13:01 UTC by Martian42

### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #157 

 

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Datasets/%23157-Correct%20US%20steel%20section%20properties%20with%20larger%20than%202%20percent%20difference?csf=1&web=1&e=pyIwrm

 ### Changelog

 ### Additional comments

 The inaccuracy is from the catalogue side. All values which is higher than 2% diff between BHoM and catalogue value has been updated to BHoM value.

2024-07-12 11:11 UTC, peterjamesnugent commented
@BHoMBot check dataset-compliance

2024-07-12 15:49 UTC, peterjamesnugent submitted a review, later dismissed
Happy to approve this - the `/develop` branch has nearly 300 properties above the 2% threshold - so great that this has been picked up to highlight errors in the source data. We should highlight this to the AISC so they can update their catalouges.

I do get some above 2% but on inspection the numbers are exactly the same, despite no rounding (and the numbers are small enough that differences are miniscule):
![image](https://github.com/user-attachments/assets/4a3d6e25-1665-46c0-962e-ccf9d0582604)

2024-07-12 15:49 UTC, peterjamesnugent commented
@BHoMBot check required

2024-07-12 15:53 UTC, peterjamesnugent requested changes
@Martian42, I believe you have serialised the `Dataset` with rounded values, can you reserialise the dataset without any rounding please so it is identical between the BHoMDataset and our Integration methods (otherwise we are just adding a %Diff for no reason).

![image](https://github.com/user-attachments/assets/a27787c4-5734-46e9-b5a7-3e86d4ad3f7f)

2024-07-17 15:13 UTC, Martian42 commented
> @Martian42, I believe you have serialised the `Dataset` with rounded values, can you reserialise the dataset without any rounding please so it is identical between the BHoMDataset and our Integration methods (otherwise we are just adding a %Diff for no reason).
> 
> ![image](https://private-user-images.githubusercontent.com/30078587/348320725-a27787c4-5734-46e9-b5a7-3e86d4ad3f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjkzODgsIm5iZiI6MTcyMTIyOTA4OCwicGF0aCI6Ii8zMDA3ODU4Ny8zNDgzMjA3MjUtYTI3Nzg3YzQtNTczNC00NmU5LWI1YTctM2U4NmQ0YWQzZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE1MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWI0ZTNkNmNhYTBjYjQ1MDI2MzFlNDU5MjE3YTZkOTJjNmQ0MzRmYmE0NzQ3N2ViODAzZTFjOTczMzNlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9UI8ixQ4YJyFC_K1PwH68rJouXJ_pdgAeO5J2mwl2n8)

Thanks @peterjamesnugent, correctly formatted the BHoM values, test script no longer showing anything over 2% diff!
![image](https://github.com/user-attachments/assets/1e2bb877-1082-43fa-b763-0d7250c848a7)

2024-07-26 14:23 UTC, peterjamesnugent commented
@BHoMBot check compliance

2024-07-26 14:24 UTC, peterjamesnugent approved these changes

2024-07-31 09:12 UTC, peterjamesnugent approved these changes
Happy changes have been made and values > 2% deviance have been updated. As mentioned earlier, worth reaching out to the source of the data to update their catalouge.

2024-07-31 09:12 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2024-07-31 09:43 UTC, peterjamesnugent commented
@BHoMBot check required

2024-07-31 12:20 UTC, peterjamesnugent commented
@BHoMBot check ready-to-merge

2024-10-04 09:57 UTC, IsakNaslundBh commented
Before this is being merged, can it please be reviewd by a US engineer. I seem to remeber that when these dataset where first generated, this difference was found, but that the decision made back then was to keep the catalogue values, as that is what is the more defining metric for a particular section, rather than the exact dimensions down to the last root radius.

Before moving away from these catalogue values, I think that it needs to be confirmed by a US structural engineer with enough experience.

2024-10-04 10:00 UTC, IsakNaslundBh commented
For not to elaborate reference on the above, please see https://github.com/BHoM/BHoM_Datasets/pull/5#pullrequestreview-255809782

2025-03-24 15:30 UTC, NikotaLitzin approved these changes
After discussion with Dmitri Lamianski (US STR Tech Lead + STR Engineer), design values in US workflows are typically derived from analysis software for design. As a result, it is not critical that the BHoM section properties follow the catalogue, so the BHoM dev approach of aligning to calc value is perfectly acceptable.

2025-03-25 21:50 UTC, merged